stages:
  - monitor
  - resource_download
  - build
  - deploy

resource_download:
  stage: resource_download
  tags:
    - shell
  script:
    - echo "Resource downloaded from external server"
  rules:
    - if: $IS_COBRAND_BUILD == "true"
      when: always
    - if: $CI_PIPELINE_SOURCE != "schedule"

build_project:
  stage: build
  tags:
    - shell
  before_script:
    - chmod +x generate_swifttlint_filelist.sh
    - ./generate_swifttlint_filelist.sh
  script:
    - |
      chmod +x ./Script/build.sh
      echo "$SYS_PASS" | sudo -S mkdir buildSudo
      if [[ -n "$COLLECT_LOG" && "$COLLECT_LOG" == "true" ]]; then
        echo "Within If condition"
        mkdir output
        ./Script/build.sh > output/build.log
      else
        echo "Within else block"
        ./Script/build.sh
      fi
  after_script:
    # - echo "$SYS_PASS" | sudo -S rm -rf buildSudo
    - rm -rf build
  # artifacts:
  #   when: always
  #   paths:
  #     - output
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

deploy_project:
  stage: deploy
  tags:
    - docker
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 cp --recursive ./output s3://cobrandbuild --endpoint-url https://v1r0.va.idrivee2-20.com
  environment: production
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"

heartbeat_job:
  stage: monitor
  tags:
    - shell
  script:
    - echo "Schedule job called"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
