stages:
  - build

build_project:
  stage: build
  tags:
    - macos
  script:
    - chmod +x ./Script/build.sh
    - ./Script/build.sh > logs.log

  artifacts:
    when: always
    paths:
      - logs.log

  