stages:
  - build

build_project:
  stage: build
  script:
    - |
      echo "$(which brew)"
      # which -s brew
      # if [[ $? != 0 ]] ; then=
      #   echo "Homebrew not installed!!!!!"
      # else
      #    echo "Homebrew installed already"
      # fi
      # - xcodebuild -project MusicPlayer.xcodeproj -target MusicPlayer -configuration Release
  tags:
    - macos