stages:
  - build

build_project:
  stage: build
  tags:
    - macos
  script:
    - echo "Build process started"
    - ls
    - pwd
    - echo "$CI_PROJECT_DIR"
    - chmod +x ./scripts/build.sh
    - ./scripts/build.sh

  