stages:
  - build

build_project:
  stage: build
  tags:
    - macos
  before_script:
    - chmod +x generate_swifttlint_filelist.sh
    - ./generate_swifttlint_filelist.sh
  script:
    - chmod +x ./Script/build.sh
    - ./Script/build.sh > logs.log
  artifacts:
    when: always
    paths:
      - logs.log