stages:
  - build

build_project:
  stage: build
  script:
    - echo 'Build process initiated'
    # - xcodebuild -project MusicPlayer.xcodeproj -target MusicPlayer -configuration Release
  tags:
    - macos