stages:
  # - pre_actions
  - build

# pre_action:
#   stage: pre_actions
#   tags:
#     - macos
#   script:
#     - chmod +x generate_swifttlint_filelist.sh
#     - ./generate_swifttlint_filelist.sh
#   cache:
#     key: input-files
#     paths:
#       - input_file/

build_project:
  stage: build
  tags:
    - macos
  pre_script:
    - chmod +x generate_swifttlint_filelist.sh
    - ./generate_swifttlint_filelist.sh
  script:
    - chmod +x ./Script/build.sh
    - ./Script/build.sh > logs.log
  artifacts:
    when: always
    paths:
      - logs.log