stages:
  - build

build_project:
  stage: build
  tags:
    - macos
  before_script:
    - chmod +x generate_swifttlint_filelist.sh
    - ./generate_swifttlint_filelist.sh
  script:
    - |
      chmod +x ./Script/build.sh
      if [[ -n "$COLLECT_LOG" && "$COLLECT_LOG" == "true" ]]; then
        echo "Within If condition"
        ./Script/build.sh > logs.log
      else
        echo "Within else block"
        ./Script/build.sh
      fi
  after_script:
    - rm -rf build
  artifacts:
    when: always
    paths:
      - logs.log